{
 "title": "PostgreSQL Overview",
 "tags": [
  "Percona",
  "PostgreSQL"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   { "name": "host", "label": "Host", "query": "label_values(pg_up,instance)" },
   {
    "name": "db",
    "label": "DB",
    "query": "label_values(pg_stat_database_tup_fetched{instance=\"$host\",datname!~\"template.*|postgres\"},datname)"
   },
   {
    "name": "version",
    "query": "label_values(pg_static,version)"
   },
   {
    "name": "max_connections",
    "query": "query_result(pg_settings_max_connections{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "shared_buffers",
    "query": "query_result(pg_settings_shared_buffers_bytes{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "work_mem",
    "query": "query_result(pg_settings_work_mem_bytes{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "wal_buffers",
    "query": "query_result(pg_settings_wal_buffers_bytes{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "wal_segment_size",
    "query": "query_result(pg_settings_wal_segment_size_bytes{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "maintenance_work_mem",
    "query": "query_result(pg_settings_maintenance_work_mem_bytes{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "block_size",
    "query": "query_result(pg_settings_block_size{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "checkpoint_segments",
    "query": "query_result(pg_settings_checkpoint_segments{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "checkpoint_timeout",
    "query": "query_result(pg_settings_checkpoint_timeout_seconds{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "default_statistics_target",
    "query": "query_result(pg_settings_default_statistics_target{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "seq_page_cost",
    "query": "query_result(pg_settings_seq_page_cost{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "random_page_cost",
    "query": "query_result(pg_settings_random_page_cost{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "effective_cache_size",
    "query": "query_result(pg_settings_effective_cache_size_bytes{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "effective_io_concurrency",
    "query": "query_result(pg_settings_effective_io_concurrency{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "fsync",
    "query": "query_result(pg_settings_fsync{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "autovacuum",
    "query": "query_result(pg_settings_autovacuum{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "autovacuum_analyze_scale_factor",
    "query": "query_result(pg_settings_autovacuum_analyze_scale_factor{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "autovacuum_analyze_threshold",
    "query": "query_result(pg_settings_autovacuum_analyze_threshold{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "autovacuum_vacuum_scale_factor",
    "query": "query_result(pg_settings_autovacuum_vacuum_scale_factor{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "autovacuum_vacuum_threshold",
    "query": "query_result(pg_settings_autovacuum_vacuum_threshold{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "autovacuum_vacuum_cost_limit",
    "query": "query_result(pg_settings_autovacuum_vacuum_cost_limit{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "autovacuum_vacuum_cost_delay",
    "query": "query_result(pg_settings_autovacuum_vacuum_cost_delay_seconds{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "autovacuum_max_workers",
    "query": "query_result(pg_settings_autovacuum_max_workers{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "autovacuum_naptime",
    "query": "query_result(pg_settings_autovacuum_naptime_seconds{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "autovacuum_freeze_max_age",
    "query": "query_result(pg_settings_autovacuum_freeze_max_age{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "logging_collector",
    "query": "query_result(pg_settings_logging_collector{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "log_min_duration_statement",
    "query": "query_result(pg_settings_log_min_duration_statement_seconds{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "log_duration",
    "query": "query_result(pg_settings_log_duration{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "log_lock_waits",
    "query": "query_result(pg_settings_log_lock_waits{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "max_wal_senders",
    "query": "query_result(pg_settings_max_wal_senders{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "max_wal_size",
    "query": "query_result(pg_settings_max_wal_size_bytes{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "min_wal_size",
    "query": "query_result(pg_settings_min_wal_size_bytes{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "wal_compression",
    "query": "query_result(pg_settings_wal_compression{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "max_worker_processes",
    "query": "query_result(pg_settings_max_worker_processes{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "max_parallel_workers_per_gather",
    "query": "query_result(pg_settings_max_parallel_workers_per_gather{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "max_parallel_workers",
    "query": "query_result(pg_settings_max_parallel_workers_per_gather{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "autovacuum_work_mem",
    "query": "query_result(pg_settings_autovacuum_work_mem_bytes{instance=\"$host\",job=\"postgresql\"})"
   },
   {
    "name": "autovacuum_multixact_freeze_max_age",
    "query": "query_result(pg_settings_autovacuum_multixact_freeze_max_age{instance=\"$host\",job=\"postgresql\"})"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "<h1><i><font color=#5991A7><b><center>Data for </font><font color=#e68a00>$host</font> <font color=#5991A7> with</font> </font><font color=#e68a00>$interval</font> <font color=#5991A7>resolution</center></b></font></i></h1><br>"
  },
  {
   "title": "Connected",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "pg_up{instance=\"$host\",job=\"postgresql\"}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "content": "<h1><b><font color=#e68a00><center>$version</center></font></b></h1>"
  },
  {
   "title": "Max Connections",
   "type": "singlestat",
   "description": "PostgreSQL's effective_cache_size variable tunes how much RAM you expect to be available for disk caching.  Generally adding Linux free+cached will give you a good idea.  This value is used by the query planner whether plans will fit in memory, and when defined too low, can lead to some plans rejecting certain indexes.",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 3 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_max_connections{instance=\"$host\",datname=~\"$db\",datname!~\"template.*|postgres\"}[$interval]) or\nmax_over_time(pg_settings_max_connections{instance=\"$host\",datname=~\"$db\",datname!~\"template.*|postgres\"}[5m])"
    }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "singlestat",
   "description": "Defines the amount of memory the database server uses for shared memory buffers.  Default is 128MB.  Guidance on tuning is 25% of RAM, but generally doesn't exceed 40%.",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_shared_buffers_bytes{instance=\"$host\",datname=~\"$db\",datname!~\"template.*|postgres\"}[$interval]) or\nmax_over_time(pg_settings_shared_buffers_bytes{instance=\"$host\",datname=~\"$db\",datname!~\"template.*|postgres\"}[5m]) "
    }
   ]
  },
  {
   "title": "Disk-Page Buffers",
   "type": "singlestat",
   "description": "The setting wal_buffers defines how much memory is used for caching the write-ahead log entries. Generally this value is small (3% of shared_buffers value), but it may need to be modified for heavily loaded servers.",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_wal_buffers_bytes{instance=\"$host\",datname=~\"$db\",datname!~\"template.*|postgres\"}[$interval]) or\nmax_over_time(pg_settings_wal_buffers_bytes{instance=\"$host\",datname=~\"$db\",datname!~\"template.*|postgres\"}[5m])"
    }
   ]
  },
  {
   "title": "Memory Size for each Query",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_work_mem_bytes{instance=\"$host\",datname=~\"$db\",datname!~\"template.*|postgres\"}[$interval]) or\nmax_over_time(pg_settings_work_mem_bytes{instance=\"$host\",datname=~\"$db\",datname!~\"template.*|postgres\"}[5m])"
    }
   ]
  },
  {
   "title": "Disk Cache Size",
   "type": "singlestat",
   "description": "The maximum number of client connections allowed.  Change this value with care as there are some memory resources that are allocated on a per-client basis, so setting max_connections higher will generally increase overall PostgreSQL memory usage.",
   "gridPos": { "h": 2, "w": 3, "x": 19, "y": 3 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_effective_cache_size_bytes{instance=\"$host\",datname=~\"$db\",datname!~\"template.*|postgres\"}[$interval]) or\nmax_over_time(pg_settings_effective_cache_size_bytes{instance=\"$host\",datname=~\"$db\",datname!~\"template.*|postgres\"}[5m])"
    }
   ]
  },
  {
   "title": "Autovacuum",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(pg_settings_autovacuum{instance=\"$host\",datname=~\"$db\",datname!~\"template.*|postgres\"}[$interval]) or\nmax_over_time(pg_settings_autovacuum{instance=\"$host\",datname=~\"$db\",datname!~\"template.*|postgres\"}[5m])"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "PostgreSQL Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(max_over_time(pg_stat_activity_count{instance=\"$host\",datname=~\"$db\",datname!~\"template.*|postgres\"}[$interval]) or\nmax_over_time(pg_stat_activity_count{instance=\"$host\",datname=~\"$db\",datname!~\"template.*|postgres\"}[5m])) by (state)",
     "legendFormat": "{{state}}"
    },
    {
     "expr": "sum(max_over_time(pg_stat_activity_count{instance=\"$host\",datname=~\"$db\",datname!~\"template.*|postgres\"}[$interval]) or\nmax_over_time(pg_stat_activity_count{instance=\"$host\",datname=~\"$db\",datname!~\"template.*|postgres\"}[5m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(pg_stat_database_numbackends{datname=~\"$db\",instance=\"$host\",datname!~\"template.*|postgres\"}[$interval]) or \nmax_over_time(pg_stat_database_numbackends{datname=~\"$db\",instance=\"$host\",datname!~\"template.*|postgres\"}[5m])",
     "legendFormat": "{{datname}}"
    },
    {
     "expr": "max_over_time(pg_settings_max_connections{instance=\"$host\"}[$interval]) or \nmax_over_time(pg_settings_max_connections{instance=\"$host\"}[5m])",
     "legendFormat": "Maximum connections"
    }
   ]
  },
  { "title": "Tuples", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Tuples",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{datname=~\"$db\",instance=~\"$host\"}[$interval])) or \nsum(irate(pg_stat_database_tup_fetched{datname=~\"$db\",instance=~\"$host\"}[5m]))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_returned{datname=~\"$db\",instance=\"$host\"}[$interval])) or\nsum(irate(pg_stat_database_tup_returned{datname=~\"$db\",instance=\"$host\"}[5m]))",
     "legendFormat": "Returned"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{datname=~\"$db\",instance=\"$host\"}[$interval])) or\nsum(irate(pg_stat_database_tup_inserted{datname=~\"$db\",instance=\"$host\"}[5m]))",
     "legendFormat": "Inserted"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_updated{datname=~\"$db\",instance=\"$host\"}[$interval])) or\nsum(irate(pg_stat_database_tup_updated{datname=~\"$db\",instance=\"$host\"}[5m]))",
     "legendFormat": "Updated"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_deleted{datname=~\"$db\",instance=\"$host\"}[$interval])) or\nsum(irate(pg_stat_database_tup_deleted{datname=~\"$db\",instance=\"$host\"}[5m]))",
     "legendFormat": "Deleted"
    }
   ]
  },
  {
   "title": "Read Tuple Activity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_returned{instance=\"$host\"}[$interval])) or\nsum(irate(pg_stat_database_tup_returned{instance=\"$host\"}[5m]))",
     "legendFormat": "Rows returned by queries"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched{instance=\"$host\"}[$interval])) or\nsum(irate(pg_stat_database_tup_fetched{instance=\"$host\"}[5m]))",
     "legendFormat": "Rows fetched by queries"
    }
   ]
  },
  {
   "title": "Tuples Changed per $interval",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted{instance=\"$host\"}[1m])) or\nsum(irate(pg_stat_database_tup_inserted{instance=\"$host\"}[5m]))",
     "legendFormat": "Rows inserted by queries"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_updated{instance=\"$host\"}[$interval])) or\nsum(irate(pg_stat_database_tup_updated{instance=\"$host\"}[5m]))",
     "legendFormat": "Rows updated by queries"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_deleted{instance=\"$host\"}[$interval])) or\nsum(irate(pg_stat_database_tup_deleted{instance=\"$host\"}[5m]))",
     "legendFormat": "Rows deleted by queries"
    }
   ]
  },
  { "title": "Transactions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit{instance=\"$host\"}[$interval])) or \nsum(irate(pg_stat_database_xact_commit{instance=\"$host\"}[5m]))",
     "legendFormat": "Commits"
    },
    {
     "expr": "sum(rate(pg_stat_database_xact_rollback{instance=\"$host\"}[$interval])) or\nsum(irate(pg_stat_database_xact_rollback{instance=\"$host\"}[5m]))",
     "legendFormat": "Rollbacks"
    }
   ]
  },
  {
   "title": "Duration of Transactions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max_over_time(pg_stat_activity_max_tx_duration{instance='$host'}[$interval]) or\nmax_over_time(pg_stat_activity_max_tx_duration{instance='$host'}[5m])",
     "legendFormat": "{{state}}"
    }
   ]
  },
  { "title": "Temp Files", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Number of Temp Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max_over_time(pg_stat_database_temp_files{instance=~\"$host\",datname!~\"template.*|postgres\"}[$interval]) or \nmax_over_time(pg_stat_database_temp_files{instance=~\"$host\",datname!~\"template.*|postgres\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  {
   "title": "Size of Temp Files",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "max_over_time(pg_stat_database_temp_bytes{instance=~\"$host\",datname!~\"template.*|postgres\"}[$interval]) or \nmax_over_time(pg_stat_database_temp_bytes{instance=~\"$host\",datname!~\"template.*|postgres\"}[5m])",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  { "title": "Conflicts & Locks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Conflicts/Deadlocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "conflicts",
     "expr": "sum(rate(pg_stat_database_deadlocks{datname=~\"$db\",instance=\"$host\"}[$interval])) or \nsum(irate(pg_stat_database_deadlocks{datname=~\"$db\",instance=\"$host\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Deadlocks",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "deadlocks",
     "expr": "sum(rate(pg_stat_database_conflicts{datname=~\"$db\",instance=\"$host\"}[$interval])) or \nsum(irate(pg_stat_database_conflicts{datname=~\"$db\",instance=\"$host\"}[5m]))",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Conflicts",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "deadlocks" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Number of Locks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "conflicts",
     "expr": "max_over_time(pg_locks_count{datname=~\"$db\",instance=\"$host\",datname!~\"template.*|postgres\"}[$interval]) or\nmax_over_time(pg_locks_count{datname=~\"$db\",instance=\"$host\",datname!~\"template.*|postgres\"}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{mode}} - {{datname}}",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "conflicts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Buffers & Blocks Operations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "Operations with Blocks",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_database_blk_read_time{datname=~\"$db\",instance=\"$host\",datname!~\"template.*|postgres\"}[$interval]) or\nirate(pg_stat_database_blk_read_time{datname=~\"$db\",instance=\"$host\",datname!~\"template.*|postgres\"}[5m])",
     "legendFormat": "Read {{datname}}"
    },
    {
     "expr": "rate(pg_stat_database_blk_write_time{datname=~\"$db\",instance=\"$host\",datname!~\"template.*|postgres\"}[$interval]) or\nirate(pg_stat_database_blk_write_time{datname=~\"$db\",instance=\"$host\",datname!~\"template.*|postgres\"}[5m])",
     "legendFormat": "Write {{datname}}"
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_alloc{instance='$host'}[$interval]) or \nirate(pg_stat_bgwriter_buffers_alloc{instance='$host'}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Allocated",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_backend_fsync{instance='$host'}[$interval]) or\nirate(pg_stat_bgwriter_buffers_backend_fsync{instance='$host'}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Fsync calls by a backend",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_backend{instance='$host'}[$interval]) or\nirate(pg_stat_bgwriter_buffers_backend{instance='$host'}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Written directly by a backend",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_clean{instance='$host'}[$interval]) or \nirate(pg_stat_bgwriter_buffers_clean{instance='$host'}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Written by the background writer",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "Buffers Allocated",
     "expr": "rate(pg_stat_bgwriter_buffers_checkpoint{instance='$host'}[5m]) or\nirate(pg_stat_bgwriter_buffers_checkpoint{instance='$host'}[5m])",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "Written during checkpoints",
     "measurement": "postgresql",
     "select": [
      [
       { "params": [ "buffers_alloc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [],
        "type": "difference"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  { "title": "Others", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "Canceled Queries",
   "type": "graph",
   "description": "Based on pg_stat_database_conflicts view",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_bufferpin{instance=\"$host\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_bufferpin{instance=\"$host\"}[5m]))",
     "legendFormat": "Pinned buffers"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_deadlock{instance=\"$host\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_deadlock{instance=\"$host\"}[5m]))",
     "legendFormat": "Deadlocks"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_lock{instance=\"$host\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_lock{instance=\"$host\"}[5m]))",
     "legendFormat": "Lock timeouts"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_snapshot{instance=\"$host\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_snapshot{instance=\"$host\"}[5m]))",
     "legendFormat": "Old snapshots"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_confl_tablespace{instance=\"$host\"}[$interval])) or\nsum(irate(pg_stat_database_conflicts_confl_tablespace{instance=\"$host\"}[5m]))",
     "legendFormat": "Dropped tablespaces "
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit{datname=~\"$db\",instance=\"$host\",datname!~\"template.*|postgres\"}) by (datname) /\n(sum(pg_stat_database_blks_hit{datname=~\"$db\",instance=\"$host\",datname!~\"template.*|postgres\"}) by (datname) + \nsum(pg_stat_database_blks_read{datname=~\"$db\",instance=\"$host\",datname!~\"template.*|postgres\"}) by (datname))",
     "legendFormat": "Cache hit rate {{datname}}"
    }
   ]
  },
  {
   "title": "Checkpoint stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(pg_stat_bgwriter_checkpoint_sync_time{instance='$host'}[$interval]) or\nirate(pg_stat_bgwriter_checkpoint_sync_time{instance='$host'}[5m])",
     "legendFormat": "Files Synchronization to disk"
    },
    {
     "expr": "rate(pg_stat_bgwriter_checkpoint_write_time{instance='$host'}[$interval]) or\nirate(pg_stat_bgwriter_checkpoint_write_time{instance='$host'}[5m])",
     "legendFormat": "Written Files to disk"
    }
   ]
  },
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 84 },
   "collapsed": true,
   "panels": [
    {
     "title": "PostgreSQL Settings",
     "type": "text",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 13 },
     "content": "<table style=\"width:100%; border: 2px solid grey;\">\n  <tr><td></td><td></td><td></td><td></td></tr>\n  <tr><td> The maximum number of concurrent connections </td><td>${max_connections}</td><td> Shared memory buffers (bytes) </td><td>${shared_buffers}</td></tr>\n  <tr><td> The maximum memory to be used for query workspaces (bytes)</td><td>${work_mem}</td><td> The number of disk-page buffers in shared memory for WAL (bytes)</td><td>${wal_buffers}</td></tr>\n  <tr><td> The number of pages per write ahead log segment (bytes) </td><td>${wal_segment_size}</td><td>The maximum memory to be used for query workspaces (bytes)</td><td>${maintenance_work_mem}</td></tr>\n  <tr><td> The block size in the write ahead log </td><td>${block_size}</td><td>The maximum distance in log segments between automatic WAL checkpoints</td><td>${checkpoint_segments}</td></tr>\n  <tr><td> Time spent flushing dirty buffers during checkpoint, as fraction of checkpoint interval </td><td>${checkpoint_timeout}</td><td>The maximum number of simultaneously running WAL sender processes</td><td>${max_wal_senders}</td></tr>\n  <tr><td> The minimum size to shrink the WAL to (bytes)</td><td>${min_wal_size}</td><td>The WAL size that triggers a checkpoint (bytes)</td><td>${max_wal_size}</td></tr>\n  <tr><td> Compresses full-page writes written in WAL file </td><td>${wal_compression}</td><td>Maximum number of concurrent worker processes</td><td>${max_worker_processes}</td></tr>\n  <tr><td> The maximum number of parallel processes per executor node </td><td>${max_parallel_workers_per_gather}</td><td>The maximum number of parallel processes per executor node</td><td>${max_parallel_workers}</td></tr>\n  <tr><td> The default statistics target </td><td>${default_statistics_target}</td><td>The planner's estimate of the cost of a sequentially fetched disk page </td><td>${seq_page_cost}</td></tr>\n  <tr><td> The planner's estimate of the cost of a nonsequentially fetched disk page </td><td>${random_page_cost}</td><td>The planner's assumption about the size of the disk cache</td><td>${effective_cache_size}</td></tr>\n  <tr><td> Number of simultaneous requests that can be handled efficiently by the disk subsystem </td><td>${effective_io_concurrency}</td><td>Forces synchronization of updates to disk </td><td>${fsync}</td></tr>\n  <tr><td> Starts the autovacuum subprocess </td><td>${autovacuum}</td><td>Number of tuple inserts, updates, or deletes prior to analyze as a fraction of reltuples</td><td>${autovacuum_analyze_scale_factor}</td></tr>\n  <tr><td> Minimum number of tuple inserts, updates, or deletes prior to analyze </td><td>${autovacuum_analyze_threshold}</td><td>Number of tuple updates or deletes prior to vacuum as a fraction of reltuples</td><td>${autovacuum_vacuum_scale_factor}</td></tr>\n  <tr><td> Minimum number of tuple updates or deletes prior to vacuum </td><td>${autovacuum_vacuum_threshold}</td><td>Vacuum cost amount available before napping, for autovacuum </td><td>${autovacuum_vacuum_cost_limit}</td></tr>\n  <tr><td> Vacuum cost delay in milliseconds, for autovacuum (seconds) </td><td>${autovacuum_vacuum_cost_delay}</td><td> The maximum number of simultaneously running autovacuum worker processes </td><td>${autovacuum_max_workers}</td></tr>\n  <tr><td> Time to sleep between autovacuum runs (seconds) </td><td>${autovacuum_naptime}</td><td>Age at which to autovacuum a table to prevent transaction ID wraparound </td><td>${autovacuum_freeze_max_age}</td></tr>\n  <tr><td> The maximum memory to be used by each autovacuum worker process (bytes)</td><td>${autovacuum_work_mem}</td><td>Multixact age at which to autovacuum a table to prevent multixact wraparound</td><td>${autovacuum_multixact_freeze_max_age}</td></tr>\n  <tr><td> Start a subprocess to capture stderr output and/or csvlogs into log files </td><td>${logging_collector}</td><td>Sets the minimum execution time above which statements will be logged (seconds) </td><td>${log_min_duration_statement}</td></tr>\n  <tr><td> Logs the duration of each completed SQL statement </td><td>${log_duration}</td><td>Logs long lock waits </td><td>${log_lock_waits}</td></tr>\n  <tr><td></td><td></td><td></td><td></td></tr>\n</table>\n\n"
    }
   ]
  },
  {
   "title": "System Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode!=\"idle\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{instance=~\"$host\", mode!=\"total\", mode!=\"idle\"}[$interval]) or \navg_over_time(node_cpu_average{instance=~\"$host\", mode!=\"total\", mode!=\"idle\"}[5m]))),100)",
       "legendFormat": "{{mode}}"
      },
      {}
     ]
    },
    {
     "title": "Saturation and Max Core Usage",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(avg_over_time(node_procs_running{instance=\"$host\"}[$interval])-1) / scalar(count(node_cpu{mode=\"user\", instance=\"$host\"})) or (avg_over_time(node_procs_running{instance=\"$host\"}[5m])-1) / scalar(count(node_cpu{mode=\"user\", instance=\"$host\"}))",
       "legendFormat": "Normalized CPU Load"
      },
      {
       "expr": "clamp_max(max by () (sum  by (cpu) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )),1)",
       "legendFormat": "Max CPU Core Utilization"
      },
      {
       "expr": "avg_over_time(node_procs_blocked{instance=\"$host\"}[$interval]) or avg_over_time(node_procs_blocked{instance=\"$host\"}[5m])",
       "legendFormat": "IO Load"
      }
     ]
    },
    {
     "title": "Disk I/O and Swap Activity",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "Bps", "label": "Page Out (-) / Page In (+)" }
     ],
     "targets": [
      {
       "expr": "rate(node_vmstat_pgpgin{instance=\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=\"$host\"}[5m]) * 1024",
       "legendFormat": "Disk Reads (Page In)"
      },
      {
       "expr": "(rate(node_vmstat_pgpgout{instance=\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=\"$host\"}[5m]) * 1024)",
       "legendFormat": "Disk Writes (Page Out)"
      },
      {
       "expr": "(rate(node_vmstat_pgpgin{instance=\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=\"$host\"}[5m]) * 1024 ) + \n(rate(node_vmstat_pgpgout{instance=\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=\"$host\"}[5m]) * 1024)",
       "legendFormat": "Total"
      },
      {
       "expr": "rate(node_vmstat_pswpin{instance=\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{instance=\"$host\"}[5m]) * 4096",
       "legendFormat": "Swap In (Reads)"
      },
      {
       "expr": "rate(node_vmstat_pswpout{instance=\"$host\"}[$interval]) * 4096 or \nirate(node_vmstat_pswpout{instance=\"$host\"}[5m]) * 4096",
       "legendFormat": "Swap Out (Writes)"
      }
     ]
    },
    {
     "title": "Network Traffic",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "Bps", "label": "Outbound (-) / Inbound (+)" }
     ],
     "targets": [
      {
       "expr": "sum(rate(node_network_receive_bytes{instance=\"$host\", device!=\"lo\"}[$interval])) or \nsum(irate(node_network_receive_bytes{instance=\"$host\", device!=\"lo\"}[5m])) or \nsum(max_over_time(rdsosmetrics_network_rx{instance=\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_rx{instance=\"$host\"}[5m])) ",
       "legendFormat": "Inbound"
      },
      {
       "expr": "sum(rate(node_network_transmit_bytes{instance=\"$host\", device!=\"lo\"}[$interval])) or sum(irate(node_network_transmit_bytes{instance=\"$host\", device!=\"lo\"}[5m])) or\nsum(max_over_time(rdsosmetrics_network_tx{instance=\"$host\"}[$interval])) or sum(max_over_time(rdsosmetrics_network_tx{instance=\"$host\"}[5m]))",
       "legendFormat": "Outbound"
      }
     ]
    }
   ]
  }
 ]
}